version: '2'
services:
  prod:
    container_name: bookmarks-node
    image: defreitas/bookmark-notes:2.1.4
    hostname: bookmarks.mageddo
    ports:
      - 3000:3000
    environment:
      - HOSTNAMES=bookmarks-node.mageddo
    volumes:
      - /var/lib/mageddo/bookmarks-node/db:/opt/bookmarks/db
      - /var/lib/mageddo/bookmarks-node/logs:/opt/bookmarks/logs
      - /var/lib/mageddo/bookmarks-node/conf:/opt/bookmarks/conf
    network_mode: bridge
  dev:
    extends: prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MG_MODE=debug
    volumes:
      - ./:/opt/bookmarks
      - ./files/prod:/opt/bookmarks/prod/sql
    command: bash -c 'npm install && sleep infinity'